### ISSUE TITLE
Query support for single variant or batch variant search 

### ISSUE THREAD

**Issue by MuhammedHasan** [furkanmtorun/gnomad_python_api#1]
Thanks a lot for the python API. 

Can you add variant search support? My use case is lookup for the MAF of the variants from gnomad.

**Comment by furkanmtorun** [comment]
Dear @MuhammedHasan,

Thanks for your comment. 
I am currently in the stage of preparing a new version of this package (maybe with a tool paper). 
So, I labeled this task as TODO and will try to add this option soon 👍 

Keep your eyes on the repo 👀 

Kind regards ✋

**Comment by furkanmtorun** [comment]
Hi Dear @MuhammedHasan,

Is there any chance for you to check the graphical user interface (GUI) of the tool in the `dev` branch for variant search via `rs_id`?

Here, what I have tried and its outputs:
![image](https://user-images.githubusercontent.com/49681382/96481153-d6283480-1243-11eb-8b77-c670d62b04c9.png)
![image](https://user-images.githubusercontent.com/49681382/96481167-daece880-1243-11eb-9b82-c858125a97f2.png)


Best regards,
Furkan
