### ISSUE TITLE
gnomad_r3 reference_genome

### ISSUE THREAD

**Issue by clairemcwhite** [furkanmtorun/gnomad_python_api#3]
```
{ 
        gene(gene_name: "TP53", reference_genome: GRCh38) {
          variants(dataset: 	gnomad_r3) {
            consequence
            pos
            rsid
            variant_id: variantId

          }  	
       }
}
```

Thanks for the useful package. Quick note, it's currently not working to format queries for gnomad_r3. The current gnomAD API requires the reference_genome in the query for gnomad_r3, otherwise you get "gnomAD v3 data is not available on reference genome GRCh37"

**Comment by furkanmtorun** [comment]
Dear Dr. McWhite,

Thanks for your comment and it is good to hear that you like this package.
I will consider adding the `reference_genome` parameter to the package.

Best,
Furkan

**Comment by furkanmtorun** [comment]
Dear Dr. McWhite,

Firstly, thank you very much for your contribution again.
I have added the `reference_genome` parameter to the package in the `dev` branch.

I hope, the new changes find you well.

Here are the screenshots for my trial.
![image](https://user-images.githubusercontent.com/49681382/96897650-7d50da00-1497-11eb-8389-27e003c6fdcf.png)
![image](https://user-images.githubusercontent.com/49681382/96897760-9f4a5c80-1497-11eb-8d88-1b09e928ba43.png)

Kind regards,
Furkan

**Comment by clairemcwhite** [comment]
Looks very nice! Thank you!

**Comment by furkanmtorun** [comment]
Hi Dear Dr. McWhite,

It is good to hear that you like the update.
Again, thanks for your contribution. 

Best regards,
Furkan
