### ISSUE TITLE
Alternative to rsid

### ISSUE THREAD

**Issue by meganpaynton** [furkanmtorun/gnomad_python_api#6]
Hello. Is there a way to alternatively search for variants without using the rsid (on GnomAD for example you can search using the genomic coordinates). Many Thanks.

**Comment by furkanmtorun** [comment]
Dear Megan Paynton (@meganpaynton) ,

Thanks for your question and your contribution. 

I have checked the API and realized that [gnomAD GraphQL API](https://gnomad.broadinstitute.org/api) also supports searching with `genomic coordinates`.

Here is an example query syntax for searching variants for [`BRCA1` in the GRCh37 build (genomic coordinates might be retrieved from Ensembl)](https://grch37.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000012048).

```
{
  region(reference_genome: GRCh37, chrom:"17", start: 41196312, stop: 41277500) {
    
    variants(dataset:gnomad_r2_1) {
      rsid
      consequence
      consequence_in_canonical_transcript
      gene_id
      gene_symbol
      transcript_id
      hgvsc
      hgvsp
      lof
      lof_filter
      lof_flags
      hgvs
    }
    structural_variants(dataset:gnomad_sv_r2_1) {
      homozygote_count
      hemizygote_count
      chrom2
      end2
      major_consequence
      length
      pos2
      type
      consequence
      ac_hom
      ac_hemi
    }
  }
}
```

Again, thank you very much for your suggestion.
I hope I can find time to integrate these new features!
Also, any coding contribution or pull requests are also welcome!

Best,
Furkan
