### ISSUE TITLE
No output when running the CLI vesion

### ISSUE THREAD

**Issue by zivlang** [furkanmtorun/gnomad_python_api#7]
Hello.

I tried running the program with the example command, such as `python gnomad_python_api/gnomad_api_cli.py -filter_by=gene_name -search_by="BRCA1" -dataset="gnomad_r3"`. An output directory was created automatically yet no files were written and no error message was printed.
For installing the program I used the git clone command and installed the required packages as instructed in the program's page.

Thanks.

**Comment by furkanmtorun** [comment]
Dear @zivlang 

The query syntaxes should be corrected according to up-to-date versions.
So, I believe that if the GraphQL queries within the code are updated, it can continue serving.
Since I am currently not able to do the required changes, it would be so great if you can send a PR.

Best,
Furkan
