### ISSUE TITLE
Can gnomAD  API be accessed in mainland  China?

### ISSUE THREAD

**Issue by loverlyday** [furkanmtorun/gnomad_python_api#8]
Hi,
Thank you very much for providing the API to access gnomAD. but when i use it in mainland China,it always Connection timed out. I want make sure that Can i use the gnomAD api in mainland China?  if not,  is there an alternative solution? 

thanks very much!!

Best
Wei Zhou

**Comment by furkanmtorun** [comment]
Dear Wei Zhou,

First of all, thank you very much for your kind words!

Currently, the tool I developed is not working as several things are getting changed and here, I could not make any updates.
Did you have a chance to give it a try on https://gnomad.broadinstitute.org/api endpoint directly?
If it does not work as well, unfortunately, I do not have any ideas or suggestions.

> Disclaimer: I am not affiliated with the gnomAD or other related teams, so my advice and comments are my own (for helping purposes).

Best,
Furkan

**Comment by loverlyday** [comment]
> Dear Wei Zhou,
> 
> First of all, thank you very much for your kind words!
> 
> Currently, the tool I developed is not working as several things are getting changed and here, I could not make any updates. Did you have a chance to give it a try on https://gnomad.broadinstitute.org/api endpoint directly? If it does not work as well, unfortunately, I do not have any ideas or suggestions.
> 
> > Disclaimer: I am not affiliated with the gnomAD or other related teams, so my advice and comments are my own (for helping purposes).
> 
> Best, Furkan

ok! i will try it ,thank you very much !

Best 
wei zhou
